# Default values for flask-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: adriangonciarz/sre-for-qas
  tag: 0.2.1
  pullPolicy: IfNotPresent
service:
  name: flask-api
  externalPort: 5000
  internalPort: 5000
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - chart-example.local
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: ingress-flask-api
    alb.ingress.kubernetes.io/target-type: instance
    kubernetes.io/ingress.class: alb
  tls:
    - secretName: chart-example-tls
      hosts:
       - chart-example.local
resources: {}